export const employees = [
  { id: 1, firstName: 'Alice', lastName: 'Smith', email: 'alice@example.com', department: 'HR', role: 'Manager' },
  { id: 2, firstName: 'Bob', lastName: 'Johnson', email: 'bob@example.com', department: 'IT', role: 'Developer' },
  { id: 3, firstName: 'Charlie', lastName: 'Lee', email: 'charlie@example.com', department: 'Finance', role: 'Analyst' },
  { id: 4, firstName: 'Diana', lastName: 'Brown', email: 'diana@example.com', department: 'Marketing', role: 'Strategist' },
  { id: 5, firstName: 'Ethan', lastName: 'Davis', email: 'ethan@example.com', department: 'Design', role: 'UX Designer' },
  { id: 6, firstName: 'Fiona', lastName: 'Miller', email: 'fiona@example.com', department: 'HR', role: 'Recruiter' },
  { id: 7, firstName: 'George', lastName: 'Wilson', email: 'george@example.com', department: 'IT', role: 'DevOps Engineer' },
  { id: 8, firstName: 'Hannah', lastName: 'Moore', email: 'hannah@example.com', department: 'Finance', role: 'Auditor' },
  { id: 9, firstName: 'Ian', lastName: 'Taylor', email: 'ian@example.com', department: 'Marketing', role: 'Content Writer' },
  { id: 10, firstName: 'Jenna', lastName: 'Anderson', email: 'jenna@example.com', department: 'Design', role: 'UI Designer' },
  { id: 11, firstName: 'Kevin', lastName: 'Thomas', email: 'kevin@example.com', department: 'HR', role: 'Coordinator' },
  { id: 12, firstName: 'Laura', lastName: 'Jackson', email: 'laura@example.com', department: 'IT', role: 'Full Stack Developer' },
  { id: 13, firstName: 'Mark', lastName: 'White', email: 'mark@example.com', department: 'Finance', role: 'Controller' },
  { id: 14, firstName: 'Nina', lastName: 'Harris', email: 'nina@example.com', department: 'Marketing', role: 'Campaign Manager' },
  { id: 15, firstName: 'Oscar', lastName: 'Martin', email: 'oscar@example.com', department: 'Design', role: 'Creative Director' },
  { id: 16, firstName: 'Paula', lastName: 'Garcia', email: 'paula@example.com', department: 'HR', role: 'Assistant' },
  { id: 17, firstName: 'Quentin', lastName: 'Martinez', email: 'quentin@example.com', department: 'IT', role: 'Security Engineer' },
  { id: 18, firstName: 'Rachel', lastName: 'Robinson', email: 'rachel@example.com', department: 'Finance', role: 'Budget Analyst' },
  { id: 19, firstName: 'Steve', lastName: 'Clark', email: 'steve@example.com', department: 'Marketing', role: 'SEO Specialist' },
  { id: 20, firstName: 'Tina', lastName: 'Rodriguez', email: 'tina@example.com', department: 'Design', role: 'Graphic Designer' },
  { id: 21, firstName: 'Bhanu', lastName: 'Dasam', email: 'bhanu@example.com', department: 'Design', role: 'Graphic Designer' },
  { id: 22, firstName: 'Priya', lastName: 'Garcia', email: 'paula@example.com', department: 'HR', role: 'Assistant' },
  { id: 23, firstName: 'Chanti', lastName: 'Martinez', email: 'quentin@example.com', department: 'IT', role: 'Security Engineer' },
  { id: 24, firstName: 'Rahul', lastName: 'Robinson', email: 'rachel@example.com', department: 'Finance', role: 'Budget Analyst' },
  { id: 25, firstName: 'Ram', lastName: 'Clark', email: 'steve@example.com', department: 'Marketing', role: 'SEO Specialist' },
  
];

